### ISSUE TITLE
ModuleNotFoundError: No module named 'external.dreamer'

### ISSUE THREAD

**Issue by rahulchhabra177** [rmsander/marl_ppo#1]
Hi, You haven't added the version of external you are using in requirements.txt.Can you please update that because I have install latest version of external and its giving me "ModuleNotFoundError: No module named 'external.dreamer'"

**Comment by rmsander** [comment]
Hi @rahulchhabra177 . Thanks for pointing this out - I've just pushed to fix this import issue. You no longer need the `external.dreamer` module - the `encode_gif` function (courtesy of the [Dreamer repo](https://github.com/google-research/dreamer)) is now available in `./ppo/utils.py`. Feel free to open this issue again if this is not resolved on your end.
