### ISSUE TITLE
Trained Model Unavailable

### ISSUE THREAD

**Issue by rahulchhabra177** [rmsander/marl_ppo#2]
Can you please share the trained model too?

**Comment by rmsander** [comment]
Hi @rahulchhabra177, thanks for reaching out about this. I have added trained models for:

(i) Single-agent (1 car, 1 agent)
(ii) Multi-agent (2 cars, 2 agents)
(iii) Self-play (2 cars, 1 agent)

These can be found in the directory `./ppo/ppo_policies`. To load them, please see the `README` section [`Loading Trained Policies`](https://github.com/rmsander/marl_ppo#loading-trained-policies). 

**Example**: To load the trained, example `self_play` policy in `ppo/ppo_policies/self_play`,
you can do so by running the following on command-line (from `./`):
```
python3 ppo/load_policies.py -p ppo/ppo_policies/self_play/
```

Once you have these models loaded, you should be able to use any `tf-agents` training interface you want with them.
