### ISSUE TITLE
external/python_headers/pymem.h:142:13: fatal error: cpython/pymem.h: No such file or directory

### ISSUE THREAD

**Issue by rahulchhabra177** [rmsander/marl_ppo#3]
I am getting this error while installing the requirements even after installing python3.7-dev . It seems like another problem with external .Can you please check?

**Comment by rmsander** [comment]
Hi @rahulchhabra177, thanks for reaching out about this. That error is strange - after installing the environment from scratch using `conda` and then `pip` (steps outlined exactly below), I could not reproduce this error. I will add the following installation steps to the `README` as a recommended installation procedure:

1. **Create new conda environment**: `conda create -n marl_ppo python=3.7`
2. **Activate new conda environment**: `conda activate marl_ppo`
2. **Change to install directory**: `cd install`
3. **Install pip packages without caching**: `pip3 install -r requirements.txt --no-cache-dir`
4. **Change to main directory**: `cd ..`
5. **Test PPO Training**: `python3 ppo/ppo_marl.py`.

For reference, here are the versions of `python`, `conda`, and `pip3` that I am using:

1. `python`: `Python 3.7.10`
2. `conda`: `conda 4.8.5`
3. `pip3`: `pip 21.1.2`

I don't believe anything should need to interface with the `external` directory anymore, but if you're still seeing this issue, please let me know, and I will help as able.
